services:
  backend:
    build: ./backend
    ports:
      - "7000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ig_sessions:/app/sessions
    networks:
      - default
      - cloudflare-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "2000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://media-saver-api.adkdev.in
    depends_on:
      - backend
    networks:
      - default
      - cloudflare-net
    restart: unless-stopped

volumes:
  ig_sessions:

networks:
  default:
  cloudflare-net:
    external: true
